-- 1. 注文単位の画像管理用テーブル (order_images)
CREATE TABLE IF NOT EXISTS public.order_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT NOT NULL REFERENCES public.image_orders(order_number) ON DELETE CASCADE,
    image_path TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 注文テーブルに代表画像パス用カラムを追加（任意・高速表示用）
-- ALTER TABLE public.image_orders ADD COLUMN IF NOT EXISTS actual_image_path TEXT;

-- 3. インデックス作成
CREATE INDEX IF NOT EXISTS idx_order_images_order_number ON public.order_images(order_number);

-- 4. RLS設定
ALTER TABLE public.order_images ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated" ON public.order_images FOR ALL USING (true);
