-- 1. 注文テーブル (image_orders)
CREATE TABLE IF NOT EXISTS public.image_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    goq_number TEXT,
    ship_date TEXT,
    delivery_date TEXT,
    customer_email TEXT,
    customer_name TEXT,
    recipient_name TEXT,
    gift_message TEXT,
    product_sku TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'image_sent', 'review_requested', 'completed')),
    notes TEXT,
    imported_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 商品テーブル (image_products)
CREATE TABLE IF NOT EXISTS public.image_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT UNIQUE NOT NULL,
    name TEXT,
    image_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. インデックス作成
CREATE INDEX IF NOT EXISTS idx_image_orders_status ON public.image_orders(status);
CREATE INDEX IF NOT EXISTS idx_image_orders_customer ON public.image_orders(customer_name);
CREATE INDEX IF NOT EXISTS idx_image_products_sku ON public.image_products(sku);

-- 4. RLS設定 (必要に応じて。今回は全許可)
ALTER TABLE public.image_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.image_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated" ON public.image_orders FOR ALL USING (true);
CREATE POLICY "Allow all for authenticated" ON public.image_products FOR ALL USING (true);

-- ストレージの設定はダッシュボードから 'product-images' バケットをpublicで作成してください。
